Lexi-1045 Adding figma links
liferay-design/liferay.design pull request #823
Opened 2020-10-17 07:04 UTC by victorvalle

https://issues.liferay.com/browse/LEXI-1045

2020-10-17 14:27 UTC, plhnk commented
running the deploy preview, excited to see this one in action!!

2020-10-17 14:29 UTC, plhnk reviewed
nice implementation :) did you read [Kent's post](https://kentcdodds.com/blog/use-ternaries-rather-than-and-and-in-jsx)?

2020-10-17 14:35 UTC, plhnk requested changes

2020-10-17 14:35 UTC, plhnk commented on src/markdown/lexicon/core-components/forms/text-input-localizable.md
>  description: 'A text input variation used in fields that can be translated into multiple languages.'
something is breaking the build here

2020-10-17 14:35 UTC, plhnk commented on src/markdown/lexicon/core-components/forms/text-input-localizable.md
>  description: 'A text input variation used in fields that can be translated into multiple languages.'
ah looks like you have to have a closing quote in figmaLink --> '

2020-10-19 06:57 UTC, victorvalle commented
I think that at the very beginning when I was trying to modify this code I did tertiary because I couldn't understand well the code. But then you changed it and it pretty and clean for me :). The code was longer and maybe not as beautiful as Ken's code.

We can change if you want. Although I don't know if we have false Trues plotting in our interface :)

2020-10-19 15:40 UTC, plhnk reviewed
excited for this!

2020-10-19 15:42 UTC, plhnk approved these changes

2020-10-19 15:42 UTC, merged